# Generated by Django 3.0.7 on 2020-07-19 14:03

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                blank=True, choices=[("d", "divers"), ("f", "female"), ("m", "male")], max_length=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to=users.models.user_profile_directory_path),
        ),
        migrations.AlterField(
            model_name="profile",
            name="place",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="street",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="trikotnummer",
            field=models.CharField(blank=True, max_length=3, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="zip",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
