# Generated by Django 3.0.7 on 2021-02-14 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    replaces = [
        ("events", "0001_initial"),
        ("events", "0002_auto_20200216_0059"),
        ("events", "0003_auto_20200216_0102"),
        ("events", "0004_auto_20200216_0111"),
        ("events", "0005_auto_20200216_1528"),
        ("events", "0006_auto_20200228_2109"),
        ("events", "0007_auto_20200305_1253"),
        ("events", "0008_auto_20200305_1304"),
        ("events", "0009_remove_event_category"),
        ("events", "0010_auto_20200806_2359"),
        ("events", "0011_auto_20201104_2231"),
        ("events", "0012_auto_20201105_1738"),
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
                ("street", models.CharField(blank=True, max_length=100, null=True)),
                ("place", models.CharField(blank=True, max_length=100, null=True)),
                ("slug", models.SlugField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("training", "Training"),
                            ("tournament", "Tournament"),
                            ("social", "Social Event"),
                            ("orga", "Organization Event"),
                            ("other", "Other"),
                        ],
                        default="Training",
                        max_length=20,
                    ),
                ),
                ("date", models.DateTimeField()),
                ("description", models.TextField(null=True)),
                ("visibility", models.CharField(default="public", max_length=20)),
                ("author", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                (
                    "location",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="events.Location"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PartChoice",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("choice", models.CharField(max_length=1)),
                ("choicetext", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Participation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "part",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="party",
                        to="events.PartChoice",
                    ),
                ),
                ("event", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="events.Event")),
                ("person", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="Categ",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
                ("slug", models.SlugField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="categ",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="events.Categ"),
        ),
        migrations.RemoveField(
            model_name="event",
            name="category",
        ),
        migrations.AlterField(
            model_name="event",
            name="author",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="slug",
            field=models.SlugField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="events.Location"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
