# Generated by Django 3.0.3 on 2020-02-15 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Choices",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("choice", models.CharField(max_length=1)),
                ("choicetext", models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name="participation",
            name="participation",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="events.Choices"),
        ),
    ]
