# Generated by Django 3.0.3 on 2020-02-16 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_auto_20200216_0059"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Choices",
            new_name="PartChoice",
        ),
    ]
