# Generated by Django 3.0.2 on 2020-02-11 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='participation',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No'), ('m', 'Maybe')], default='n', max_length=10),
        ),
    ]
