# Generated by Django 3.0.3 on 2020-02-14 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20200212_0001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participation',
            old_name='participants',
            new_name='person',
        ),
    ]
