# Generated by Django 3.0.7 on 2020-11-05 16:38

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20200806_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
