# Generated by Django 3.0.7 on 2020-11-05 16:38

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0011_auto_20201104_2231"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="description",
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
