# Generated by Django 3.1.12 on 2022-12-26 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_auto_20210228_1205'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Files',
            new_name='File',
        ),
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
