# Generated by Django 3.1.12 on 2022-12-26 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0005_auto_20221226_1742"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image",
            old_name="image",
            new_name="file",
        ),
    ]
