# Generated by Django 3.1.12 on 2022-12-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0007_image_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
