# Generated by Django 3.0.2 on 2020-02-09 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_auto_20200208_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='page',
            field=models.CharField(choices=[('home', 'Home'), ('tplb', 'Teamplanbuch')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('pub', 'Public'), ('mem', 'Members')], default='public', max_length=20),
        ),
    ]
