# Generated by Django 3.0.2 on 2020-02-09 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0006_auto_20200209_0145"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="page",
            field=models.CharField(choices=[("home", "Home"), ("events", "Events")], max_length=50, null=True),
        ),
    ]
