# Generated by Django 3.0.3 on 2020-03-03 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0007_auto_20200209_0202"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Post",
        ),
    ]
