# Generated by Django 3.0.7 on 2021-07-24 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ultistats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ultistats.GameMode')),
                ('pitch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ultistats.Pitch')),
                ('team_a', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_team_a', to='ultistats.Team')),
                ('team_b', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_team_b', to='ultistats.Team')),
            ],
        ),
    ]
