# Generated by Django 3.0.7 on 2020-07-04 14:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mail", "0002_auto_20200704_1610"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Mail",
            new_name="Message",
        ),
    ]
